apiVersion: v1
kind: Secret
metadata:
  name: netsoft-registry-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJuZXRzb2Z0LnRtaXQuYm1lLmh1OjUwNTAiOiB7CgkJCSJhdXRoIjogImJHVjJZV2wwT21kc2NHRjBMVU5FYm5RNE5XWjZhRkZaTlVZNGFITnhNMlZpIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
